import { JobApplicationType } from "@/types";

export const products = [
  {
    id: "728ed52f",
    price: 100,
    productname: "Ninniku Ramen",
    description: "Rich garlic-flavored ramen with savory broth and tender noodles.",
    category: "Ramen",
  },
  {
    id: "728ed52g",
    price: 130,
    productname: "Spicy Shoyu Ramen",
    description: "Soy sauce-based ramen with a spicy kick, perfect for heat lovers.",
    category: "Ramen",
  },
  {
    id: "728ed52h",
    price: 130,
    productname: "Takoyaki",
    description: "Crispy on the outside, gooey on the inside — classic octopus balls.",
    category: "Side Dish",
  },
  {
    id: "728ed52i",
    price: 90,
    productname: "Matcha Milk Tea",
    description: "Creamy matcha blended with fresh milk, a sweet refreshing drink.",
    category: "Drinks",
  },
  {
    id: "728ed52j",
    price: 110,
    productname: "Tonkotsu Ramen",
    description: "Creamy pork bone broth ramen, rich and deeply flavorful.",
    category: "Ramen",
  },
  {
    id: "728ed52k",
    price: 120,
    productname: "Miso Ramen",
    description: "Nutty, hearty miso broth with springy noodles and vegetables.",
    category: "Ramen",
  },
  {
    id: "728ed52l",
    price: 140,
    productname: "Chashu Ramen",
    description: "Tender pork belly slices atop steaming hot ramen noodles.",
    category: "Ramen",
  },
  {
    id: "728ed52m",
    price: 95,
    productname: "Yuzu Soda",
    description: "Refreshing citrusy soda with the unique aroma of Japanese yuzu.",
    category: "Drinks",
  },
  {
    id: "728ed52n",
    price: 80,
    productname: "Iced Oolong Tea",
    description: "Light and floral oolong tea served chilled, perfect for any meal.",
    category: "Drinks",
  },
  {
    id: "728ed52o",
    price: 70,
    productname: "Edamame",
    description: "Lightly salted boiled soybeans, a healthy and tasty snack.",
    category: "Side Dish",
  },
  {
    id: "728ed52p",
    price: 90,
    productname: "Gyoza",
    description: "Pan-fried dumplings filled with juicy pork and vegetables.",
    category: "Side Dish",
  },
  {
    id: "728ed52q",
    price: 105,
    productname: "Shio Ramen",
    description: "Light and clear salt-based broth with a delicate, savory flavor.",
    category: "Ramen",
  },
  {
    id: "728ed52r",
    price: 135,
    productname: "Black Garlic Ramen",
    description: "Deep, rich flavor of black garlic blended into silky tonkotsu broth.",
    category: "Ramen",
  },
  {
    id: "728ed52s",
    price: 100,
    productname: "Karaage Chicken",
    description: "Crispy Japanese-style fried chicken, juicy and flavorful inside.",
    category: "Side Dish",
  },
  {
    id: "728ed52t",
    price: 85,
    productname: "Calpico",
    description: "Sweet and tangy Japanese yogurt-based soft drink, super refreshing.",
    category: "Drinks",
  },
  {
    id: "728ed52u",
    price: 120,
    productname: "Butter Corn Ramen",
    description: "Miso ramen topped with sweet corn and a generous slab of butter.",
    category: "Ramen",
  },
  {
    id: "728ed52v",
    price: 75,
    productname: "Seaweed Salad",
    description: "Fresh, tangy seaweed salad with sesame dressing.",
    category: "Side Dish",
  },
  {
    id: "728ed52w",
    price: 150,
    productname: "Deluxe Ramen Combo",
    description: "A full set of ramen, side dish, and drink — the ultimate meal.",
    category: "Ramen",
  },
];

export const jobApplications: JobApplicationType[] = [
  {
    _id: "64d2f1034fa6e3c7a9a1e001",
    companyName: "TechNova Solutions",
    jobTitle: "Full Stack Developer",
    appliedDate: "2025-06-15",
    status: "Interview",
    interviewAt: "2025-07-12T09:00:00",
    followUp: "2025-06-29",
    salary: "₱75,000/month",
    jobType: "Full-Time Remote"
  },
  {
    _id: "64d2f1034fa6e3c7a9a1e002",
    companyName: "ByteForge Labs",
    jobTitle: "Junior Full Stack Developer",
    appliedDate: "2025-06-10",
    status: "Applied",
    interviewAt: null,
    followUp: "2025-06-24",
    salary: "₱50,000/month",
    jobType: "On-Site Full-Time"
  },
  {
    _id: "64d2f1034fa6e3c7a9a1e003",
    companyName: "DevCircle Inc.",
    jobTitle: "Mid-Level Full Stack Engineer",
    appliedDate: "2025-05-29",
    status: "Rejected",
    interviewAt: null,
    followUp: "2025-06-12",
    salary: "₱70,000/month",
    jobType: "Hybrid"
  },
  {
    _id: "64d2f1034fa6e3c7a9a1e004",
    companyName: "Nexabyte Technologies",
    jobTitle: "Full Stack Developer (React/Node)",
    appliedDate: "2025-06-01",
    status: "Interview",
    interviewAt: "2025-07-09T09:00:00",
    followUp: "2025-06-15",
    salary: "₱85,000/month",
    jobType: "Remote Contract"
  },
  {
    _id: "64d2f1034fa6e3c7a9a1e005",
    companyName: "CloudSprint",
    jobTitle: "Full Stack Engineer",
    appliedDate: "2025-06-18",
    status: "Offer",
    interviewAt: "2025-07-01T09:00:00",
    followUp: "2025-07-02",
    salary: "₱95,000/month",
    jobType: "Full-Time Remote"
  },
  {
    _id: "64d2f1034fa6e3c7a9a1e006",
    companyName: "StackHive Corp.",
    jobTitle: "React/Node Developer",
    appliedDate: "2025-07-01",
    status: "Applied",
    interviewAt: null,
    followUp: "2025-07-15",
    salary: "₱60,000/month",
    jobType: "Contract - 6 months"
  },
  {
    _id: "64d2f1034fa6e3c7a9a1e007",
    companyName: "NextFrame Studios",
    jobTitle: "Full Stack Developer Intern",
    appliedDate: "2025-06-25",
    status: "Applied",
    interviewAt: null,
    followUp: "2025-07-09",
    salary: "₱15,000/month",
    jobType: "Internship"
  },
  {
    _id: "64d2f1034fa6e3c7a9a1e008",
    companyName: "LoopEdge Tech",
    jobTitle: "Full Stack Web Developer",
    appliedDate: "2025-06-20",
    status: "Interview",
    interviewAt: "2025-07-13T09:00:00",
    followUp: "2025-07-04",
    salary: "₱72,000/month",
    jobType: "Remote Full-Time"
  },
  {
    _id: "64d2f1034fa6e3c7a9a1e009",
    companyName: "CodeWell Ventures",
    jobTitle: "Backend-Focused Full Stack Dev",
    appliedDate: "2025-06-05",
    status: "Rejected",
    interviewAt: "2025-06-25T09:00:00",
    followUp: "2025-06-19",
    salary: "₱80,000/month",
    jobType: "On-Site Full-Time"
  },
  {
    _id: "64d2f1034fa6e3c7a9a1e00a",
    companyName: "PixelCloud",
    jobTitle: "Full Stack JavaScript Engineer",
    appliedDate: "2025-07-05",
    status: "Applied",
    interviewAt: null,
    followUp: "2025-07-19",
    salary: "₱65,000/month",
    jobType: "Hybrid Remote"
  }
];


